/** Standard trade region display names (matches backend trade_regions seed). */
export const REGION_OPTIONS = [
  "US Gulf",
  "US East Coast",
  "US West Coast",
  "East Coast South America",
  "West Coast South America",
  "Caribbean",
  "West Africa",
  "East Africa",
  "Mediterranean",
  "Black Sea",
  "Continent (Amsterdam-Rotterdam-Antwerp range)",
  "UK-Continent",
  "Baltic Sea",
  "Arabian Gulf / Persian Gulf",
  "Red Sea",
  "West Coast India",
  "East Coast India",
  "Indian Subcontinent (often grouped with India range)",
  "Southeast Asia",
  "Singapore / Malacca Strait hub zone (open-position term)",
  "Far East",
  "Australia (often grouped with NZ as Oceania)",
  "UNSPECIFIED",
  "Others",
];
